services:
  - type: web
    name: smart-assistant
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: postgresql://neondb_owner:npg_Vdbu5N8flMHe@ep-late-unit-a1wmgw6u-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
        sync: false
      - key: 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
        sync: false
      - key: smartassistant.official@gmail.com
        sync: false
      - key: cgwpmbjwwjqqhudi
        sync: false
      - key: https://smart-ai-assistant-m09y.onrender.com
        sync: false
